### ISSUE TITLE
Warning in test example diff sort

### ISSUE THREAD

**Issue by doric35** [Felix-Petersen/difftopk#5]
Warning received in the DiffTopkNet example in the readme file.

UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3575.)

**Comment by Felix-Petersen** [comment]
Thanks for letting me know. After some investigation, I'm not sure how / where this is triggered. Could you give me the exact lines of python code that you executed and the output of `pip freeze`?

Best regards,

Felix
